version: "3.7"
services:
  Influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    environment:
      'NAME': "influxdb"
    volumes:
      - "./storage/influxdb:/var/lib/influxdb"
    restart: unless-stopped
    hostname: "influxdb"
    container_name: "influxdb"
  Grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    environment:
      'NAME': "grafana"
    volumes:
    - "./storage/grafana:/var/lib/grafana"
    restart: unless-stopped
    hostname: "grafana"
    container_name: "grafana"
  ScriptContainer:
    image: "script"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      'NAME': "script"
    hostname: "script"
    container_name: "script"
    volumes:
      - "./scripts:/scripts"